### ISSUE TITLE
expr

### ISSUE THREAD

**Issue by antonmedv** [hashicorp/go-bexpr#4]
Hi,

How is your day today? 🙂
Have you seen https://github.com/antonmedv/expr ?

**Comment by mkeeler** [comment]
@antonmedv I have seen your repo before and while very interesting it doesn't fit some of the goals we had for a expression syntax. Mainly to keep the language very simple and familiar to users of HashiCorp's products (especially those using Sentinel). Things like arbitrary function calls and arithmetic push the language more into a full programming language instead of what this library is supposed to be which is constrained boolean expression evaluation. For other use cases I am sure that antonmedv/expr would be the right fit, just not the specific case we were targeting that encouraged us to create this library.

**Comment by antonmedv** [comment]
I understand. Maybe I can create configuration option for **expr** to fit your goals. For example turn everything off and leave only boolean algebra. What do you think?
